name: Auto approve

on:
  workflow_dispatch:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      if: github.actor == 'dependabot[bot]'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
